name: Create Pull Request

on:
  push:
    branches:
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          branch: auto/pr-develop-to-main
          title: "Synchronisation develop → main"
          body: "Pull request générée automatiquement depuis develop."
